import os
import random
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

# List of mock company names
COMPANIES = [
    "TechCorp Solutions", "Global Logistics Ltd", "Green Energy Inc",
    "Blue Sky Ventures", "Apex Manufacturing", "Innovatech group",
    "Summit Financials", "Oceanic Shipping", "Evergreen Retail",
    "Pioneer Softworks", "Quantum Dynamics", "Starlight Media",
    "Frontier Biotech", "Velocity Auto", "Zenith Consulting"
]

def create_mock_pdf(filename, companies_to_include):
    c = canvas.Canvas(filename, pagesize=letter)
    width, height = letter

    # Header
    c.setFont("Helvetica-Bold", 10)
    c.drawString(50, height - 30, "CONFIDENTIAL BUSINESS REPORT - 2024")
    c.line(50, height - 35, width - 50, height - 35)

    # Body
    text = c.beginText(50, height - 70)
    text.setFont("Helvetica", 12)
    text.textLine("This report outlines the performance and partnerships for the current fiscal year.")
    text.textLine("")
    
    for company in companies_to_include:
        text.textLine(f"Partnership with {company} has shown significant growth.")
        text.textLine(f"Representatives from {company} will meet next week.")
        text.textLine("")

    text.textLine("End of partnership summary.")
    c.drawText(text)

    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.line(50, 50, width - 50, 50)
    c.drawString(50, 40, "Page 1 of 1")
    c.drawRightString(width - 50, 40, "Generated by MockSystem v1.0")

    c.showPage()
    c.save()

def generate_batch(count=20, output_dir="pdfs"):
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    
    for i in range(count):
        # Pick 1-3 random companies for this PDF
        selected = random.sample(COMPANIES, random.randint(1, 4))
        filename = os.path.join(output_dir, f"sample_{i+1:03d}.pdf")
        create_mock_pdf(filename, selected)
        print(f"Generated {filename}")

if __name__ == "__main__":
    generate_batch(20)
